theme: minima
title: Ying Hao's Math Ramblings
author: Kok Ying Hao
description: A place where I post notes and random projects.

header_pages:
- notes.md
- projects.md
- posts.md
- currentresearch.md

collections:
  notes:
    output: True
    permalink: /notes/:name/

  projects:
    output: True
    permalink: /projects/:name/

  research:
    output: True
    permalink: /research/:name/

plugins:
- jekyll-feed